# -*- coding: utf-8 -*-
"""Day_01_Introduction_to_Data_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMnoAEgOsIXuksm4xl3A7oRgjiiqSRCg
"""



import pandas as pd

df=pd.read_csv('student_performance (1).csv')

df.head()

df.head(10)

df.tail()

df.shape

df.shape[0:6]

print(df.columns.tolist)

print(df.name.tolist)

df.describe()

df = df[df['math_score'] != 5]
display(df.head())

print(df['department'].unique())

print(df['department'].value_counts())

print(df['gender'].value_counts())

print(df['city'].value_counts())

cs_students=df[df['department']=='Computer Science']

print(f"Number of cs students:{len(cs_students)}")

program_score=df[(df['city']=='Chennai') | (df['city']=='Mumbai')]

print(f"Prgram Score of students from Chennai and Mumbai: {len(program_score)}")

print(f"Students with attendance above 75%: {len(high_attendance)}")

df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']

top_student=df.loc[df['total_score'].idxmax()]

print("top student")
print(f"Name: {top_student['name']}")
print(f"Department: {top_student['department']}")
print(f"Total Score: {top_student['total_score']}")
print(f"Attendance Percentage: {top_student['attendance_percentage']}%")

top_student=df.loc[df['total_score'].idxmin()]

print("top student")
print(f"Name: {top_student['name']}")
print(f"Department: {top_student['department']}")
print(f"Total Score: {top_student['total_score']}")
print(f"Attendance Percentage: {top_student['attendance_percentage']}%")